### ISSUE TITLE
A kép kicsinyítés nem működik helyesen!

### ISSUE THREAD

**Issue by IllesAprod** [ingatlancom/api-client#2]
Ha 800X600-as képnél nagyobb képet küldünk rosszul méretezi át a kliens és az Api visszadobja mert nem éri el a minimális méretet.

**Comment by mefiblogger** [comment]
@IllesAprod köszi a visszajelzést, megnézzük és jelentkezünk!

**Comment by mefiblogger** [comment]
E-mailben egyeztettük, a kérésben hibásan szerepelt a kép. A hiba akkor jön elő, ha az ApiClient-nek egy 800x600-nál nagyobb képet adunk át, amit az átméretez (`$img->createResizedMaximizedImage($this->maxWidth, $this->maxHeight)`) és utána az API visszadobja, hogy túl kicsi.
