### ISSUE TITLE
Login adatok beszerzése

### ISSUE THREAD

**Issue by Duvy2** [ingatlancom/api-client#29]
Sziasztok,

ez még működik ingatlan.com-al?
a segitunk@ingatlan.com -ról elküldtek a pics-ba, hogy az életbe nem fogok kapni username/passt, mert ez már nem támogatott, pötyögjünk a weboldalon manuálisan.
Igaz ez, vagy valaki kitudna esetleg segíteni egy értelmesebb kontakttal tőlük?

**Comment by peticsi** [comment]
Szia @Duvy2! Megtennéd, hogy az elérhetőségeiddel írsz nekem egy email a szabo.peter@ingatlan.com címre? Köszönöm!
